name: Build & Release macOS Installer

on:
  release:
    types: [created]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Pillow para converter PNG->ICNS automaticamente
          pip install pillow pyinstaller

      - name: Build Summarizer.app
        run: |
          # Garante que o ícone seja .icns (Pillow cuida da conversão automática)
          pyinstaller \
            --name Summarizer \
            --windowed \
            --icon resources/icon.png \
            --add-data "resources/icon.png:resources" \
            tray_gemini.py

      - name: Create DMG installer
        run: |
          # hdiutil cria um DMG simples a partir da pasta .app
          hdiutil create dist/Summarizer.dmg \
            -volname "Summarizer" \
            -srcfolder dist/Summarizer.app \
            -ov \
            -format UDZO

      - name: Publish DMG to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/Summarizer.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
